### PR TITLE
vega: templates: Update tooltip in linear plot.

### PR DESCRIPTION
**Pull request by daavoo**
Before:

https://user-images.githubusercontent.com/12677733/202713675-9724d2c8-bb75-4b62-832a-313799eb9708.mov

Now:

https://user-images.githubusercontent.com/12677733/202713637-b503a8a3-79a9-40b6-9555-b66762f28e46.mov

### CODE REVIEW

**Comment by dberenbaum** [comment]
Great stuff! Should it also be added to the smooth template?

**Comment by daavoo** [comment]
Manually tested in Studio (work as expected):


https://user-images.githubusercontent.com/12677733/202781988-8a601513-2036-44c7-beaf-8fed3d303e24.mov



And VSCode (some minor bugs mentioned in https://iterativeai.slack.com/archives/C01RB7BTG4C/p1668777791197719)

**Comment by daavoo** [comment]
> Great stuff! Should it also be added to the smooth template?

Tried copy-pasting but the tooltip doesn't show and I had enough vega for today 😅 
Will try to get it working next week

**Comment by shcheklein** [comment]
Hey, great improvement. A couple things, I've noticed.

Here is the TB tooltip.

Screen Shot 2022-11-18 at 3 54 55 PM

- Can we keep color of a line in the tooltip (e.g. highlight name of a rev)? It's less critical if the second part could not be improved.
- Can we show all values across all lines?

**Comment by dberenbaum** [comment]
Non-blocking question: can/should it include other data fields besides `rev`, `x`, and `y`? See https://github.com/iterative/dvc/issues/7987 where threshold values are also wanted.

**Comment by daavoo** [comment]
> Non-blocking question: can/should it include other data fields besides rev, x, and y? See https://github.com/iterative/dvc/issues/7987 where threshold values are also wanted.

We would need to change some logic here and there, as the templating system only has anchors for x and y (`rev` is hardcoded)

**Comment by daavoo** [comment]
> Can we keep color of a line in the tooltip (e.g. highlight name of a rev)? It's less critical if the second part could not be improved.
> Can we show all values across all lines?

Can't really tell if it's possible or not without spending some time in the vega editor or finding an existing example

**Review by dberenbaum — APPROVED** [review]
Sorry, didn't mean to hold this up. LGTM!

**Pull request merged**
